# Generated by Django 4.2.17 on 2024-12-13 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelId', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('modelFile', models.FileField(upload_to='models/')),
                ('qrurl', models.URLField(max_length=500)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
