# Generated by Django 4.2.17 on 2024-12-13 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('armodels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armodel',
            name='modelFile',
            field=models.FileField(upload_to='ar_models/'),
        ),
    ]
